[package]
name = "rs1090"
version = "0.1.0"
edition = "2021"

[dependencies]
async-stream = "0.3.5"
deku = "0.16.0"
futures = "0.3.30"
futures-util = "0.3.30"
libm = "0.2.8"
serde = { version="1.0.197", features = ["derive"] }
serde_json = "1.0.114"
tokio = { version="1.36.0", features = ["full"] }

[dev-dependencies]
approx = "0.5.1"
hexlit = "0.5.5"
