[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
license = "MIT"
edition = "2021"
readme = "readme.md"
version = "0.1.1"

[profile.release]
lto = true
strip = true
overflow-checks = true
